set(I386 OFF)
set(X86_64 OFF)
set(ARM32 OFF)
set(ARM64 OFF)

if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i386")
    set(I386 ON)
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
    set(X86_64 ON)
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "armv7l")
    set(ARM32 ON)
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch32")
    set(ARM32 ON)
elseif (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
    set(ARM64 ON)
else ()
    message(FATAL_ERROR "Undetect architecture ${CMAKE_SYSTEM_PROCESSOR} to be configured in config.h.in")
endif ()
