name: astyle
on:
  pull_request:
    branches: [ master ]
jobs:
  astyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: install dependencies
        run: sudo apt-get install astyle

      - name: astyle check
        id: astyle
        run: |
          ARTISTIC_STYLE_OPTIONS=".astylerc" astyle -Q --recursive ./*.c,*.h > astyle.out
          TEST=$(cat astyle.out | wc -l)
          if [ $TEST -gt 3 ]; then exit 1; fi

      - name: Show required astyle changes
        if: failure()
        run: git diff
