name: compile
on:
  pull_request:
    branches: [ master ]
jobs:
  compile:
    strategy:
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'ubuntu-20.04'
        compiler:
          - 'gcc'
          - 'clang'
        builder:
          - 'autotools'
          - 'cmake'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y autoconf-archive flex bison libglib2.0-dev libjson-c-dev libxen-dev libvirt-dev libfuse-dev clang build-essential cmake
          git clone --depth=2 https://github.com/libvmi/libkvmi
          cd libkvmi
          ./bootstrap
          ./configure
          make
          sudo make install
          cd ..

      - name: Compile (cmake)
        env:
          CC: ${{ matrix.compiler }}
        if: matrix.builder == 'cmake'
        run: |
          while IFS= read -r options; do
            echo "Building with '$options'"
            mkdir -p build
            cd build
            cmake $options ..
            make
            make clean
            cd ..
            git clean -xdf
            echo "Done building with '$options'"
          done < .github/cmake_options.txt

      - name: Compile (autotools)
        env:
          CC: ${{ matrix.compiler }}
        if: matrix.builder == 'autotools'
        run: |
          while IFS= read -r options; do
            echo "Building with '$options'"
            autoreconf -vif
            ./configure $options
            make
            make clean
            git clean -xdf
            echo "Done building with '$options'"
          done < .github/configure_options.txt
